/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as ExerciseExerciseIdRouteImport } from './routes/exercise/$exerciseId'
import { Route as MusclesIndexRouteImport } from './routes/muscles/index'
import { Route as MusclesMuscleIdRouteImport } from './routes/muscles/$muscleId'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsSplitRouteImport } from './routes/settings/split'
import { Route as TimelineIndexRouteImport } from './routes/timeline/index'
import { Route as TimelineDayRouteImport } from './routes/timeline/$day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseExerciseIdRoute = ExerciseExerciseIdRouteImport.update({
  id: '/exercise/$exerciseId',
  path: '/exercise/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)
const MusclesIndexRoute = MusclesIndexRouteImport.update({
  id: '/muscles/',
  path: '/muscles/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusclesMuscleIdRoute = MusclesMuscleIdRouteImport.update({
  id: '/muscles/$muscleId',
  path: '/muscles/$muscleId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSplitRoute = SettingsSplitRouteImport.update({
  id: '/settings/split',
  path: '/settings/split',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineIndexRoute = TimelineIndexRouteImport.update({
  id: '/timeline/',
  path: '/timeline/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineDayRoute = TimelineDayRouteImport.update({
  id: '/timeline/$day',
  path: '/timeline/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/records': typeof RecordsRoute
  '/exercise/$exerciseId': typeof ExerciseExerciseIdRoute
  '/muscles/$muscleId': typeof MusclesMuscleIdRoute
  '/settings/split': typeof SettingsSplitRoute
  '/timeline/$day': typeof TimelineDayRoute
  '/muscles/': typeof MusclesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/timeline/': typeof TimelineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/records': typeof RecordsRoute
  '/exercise/$exerciseId': typeof ExerciseExerciseIdRoute
  '/muscles/$muscleId': typeof MusclesMuscleIdRoute
  '/settings/split': typeof SettingsSplitRoute
  '/timeline/$day': typeof TimelineDayRoute
  '/muscles': typeof MusclesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/timeline': typeof TimelineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/records': typeof RecordsRoute
  '/exercise/$exerciseId': typeof ExerciseExerciseIdRoute
  '/muscles/$muscleId': typeof MusclesMuscleIdRoute
  '/settings/split': typeof SettingsSplitRoute
  '/timeline/$day': typeof TimelineDayRoute
  '/muscles/': typeof MusclesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/timeline/': typeof TimelineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/records'
    | '/exercise/$exerciseId'
    | '/muscles/$muscleId'
    | '/settings/split'
    | '/timeline/$day'
    | '/muscles/'
    | '/settings/'
    | '/timeline/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/records'
    | '/exercise/$exerciseId'
    | '/muscles/$muscleId'
    | '/settings/split'
    | '/timeline/$day'
    | '/muscles'
    | '/settings'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/records'
    | '/exercise/$exerciseId'
    | '/muscles/$muscleId'
    | '/settings/split'
    | '/timeline/$day'
    | '/muscles/'
    | '/settings/'
    | '/timeline/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecordsRoute: typeof RecordsRoute
  ExerciseExerciseIdRoute: typeof ExerciseExerciseIdRoute
  MusclesMuscleIdRoute: typeof MusclesMuscleIdRoute
  SettingsSplitRoute: typeof SettingsSplitRoute
  TimelineDayRoute: typeof TimelineDayRoute
  MusclesIndexRoute: typeof MusclesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TimelineIndexRoute: typeof TimelineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise/$exerciseId': {
      id: '/exercise/$exerciseId'
      path: '/exercise/$exerciseId'
      fullPath: '/exercise/$exerciseId'
      preLoaderRoute: typeof ExerciseExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muscles/': {
      id: '/muscles/'
      path: '/muscles'
      fullPath: '/muscles/'
      preLoaderRoute: typeof MusclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muscles/$muscleId': {
      id: '/muscles/$muscleId'
      path: '/muscles/$muscleId'
      fullPath: '/muscles/$muscleId'
      preLoaderRoute: typeof MusclesMuscleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/split': {
      id: '/settings/split'
      path: '/settings/split'
      fullPath: '/settings/split'
      preLoaderRoute: typeof SettingsSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline/': {
      id: '/timeline/'
      path: '/timeline'
      fullPath: '/timeline/'
      preLoaderRoute: typeof TimelineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline/$day': {
      id: '/timeline/$day'
      path: '/timeline/$day'
      fullPath: '/timeline/$day'
      preLoaderRoute: typeof TimelineDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecordsRoute: RecordsRoute,
  ExerciseExerciseIdRoute: ExerciseExerciseIdRoute,
  MusclesMuscleIdRoute: MusclesMuscleIdRoute,
  SettingsSplitRoute: SettingsSplitRoute,
  TimelineDayRoute: TimelineDayRoute,
  MusclesIndexRoute: MusclesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TimelineIndexRoute: TimelineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
